### ISSUE TITLE
Needs Clarification

### ISSUE THREAD

**Issue by vishalpatel2890** [learn-co-curriculum/dsc-dealing-with-categorical-variables#1]
Two methods of dealing with categorical variables are introduced, label encoding and one hot encoding. However, it does not clarify which one to use when. Seems like label encoding might only have very limited applications and one hot encoding is essential in dealing with categorical variables. It would be helpful to have clarification on the right application of each one. 

For reference:
https://medium.com/@contactsunny/label-encoder-vs-one-hot-encoder-in-machine-learning-3fc273365621

**Comment by LoreDirick** [comment]
Hi @vishalpatel2890: Matt Stetz on my team made significant updates to clarify. I'm closing this now, let me know if you think we can clarify this even better! Thank you so much for raising!
